INSERT INTO PRODUTO(CODIGO,NOME,QUANTIDADE) VALUES (1,'BANANA',1000);
INSERT INTO PRODUTO(CODIGO,NOME,QUANTIDADE) VALUES (2,'MORANGO',200);
INSERT INTO PRODUTO(CODIGO,NOME,QUANTIDADE) VALUES (3,'LARANJA',700);